
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 7.3
 PARAMETER PROC_INSTANCE = microblaze_0
 PARAMETER stdin = axi_uartlite_0
 PARAMETER stdout = axi_uartlite_0
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu
 PARAMETER DRIVER_VER = 2.12
 PARAMETER HW_INSTANCE = microblaze_0
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = GPIO8
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = GPIO8_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = GPIO8
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = GPIO8_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = GPIO8
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = GPIO8_2
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = TMR
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = TMR_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = axi_i2c
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = axi_i2c_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 3.5
 PARAMETER HW_INSTANCE = axi_uartlite_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = intc
 PARAMETER DRIVER_VER = 3.12
 PARAMETER HW_INSTANCE = microblaze_0_axi_intc
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.5
 PARAMETER HW_INSTANCE = microblaze_0_local_memory_dlmb_bram_if_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.5
 PARAMETER HW_INSTANCE = microblaze_0_local_memory_ilmb_bram_if_cntlr
END


