# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/imports/Basys-3-Master.xdc

# Block Designs: bd/axi_spi/axi_spi.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_spi || ORIG_REF_NAME==axi_spi} -quiet] -quiet

# IP: bd/axi_spi/ip/axi_spi_microblaze_0_0/axi_spi_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_spi_microblaze_0_0 || ORIG_REF_NAME==axi_spi_microblaze_0_0} -quiet] -quiet

# IP: bd/axi_spi/ip/axi_spi_dlmb_v10_0/axi_spi_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_spi_dlmb_v10_0 || ORIG_REF_NAME==axi_spi_dlmb_v10_0} -quiet] -quiet

# IP: bd/axi_spi/ip/axi_spi_ilmb_v10_0/axi_spi_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_spi_ilmb_v10_0 || ORIG_REF_NAME==axi_spi_ilmb_v10_0} -quiet] -quiet

# IP: bd/axi_spi/ip/axi_spi_dlmb_bram_if_cntlr_0/axi_spi_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_spi_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==axi_spi_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/axi_spi/ip/axi_spi_ilmb_bram_if_cntlr_0/axi_spi_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_spi_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==axi_spi_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/axi_spi/ip/axi_spi_lmb_bram_0/axi_spi_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_spi_lmb_bram_0 || ORIG_REF_NAME==axi_spi_lmb_bram_0} -quiet] -quiet

# IP: bd/axi_spi/ip/axi_spi_xbar_0/axi_spi_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_spi_xbar_0 || ORIG_REF_NAME==axi_spi_xbar_0} -quiet] -quiet

# IP: bd/axi_spi/ip/axi_spi_microblaze_0_axi_periph_0/axi_spi_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_spi_microblaze_0_axi_periph_0 || ORIG_REF_NAME==axi_spi_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/axi_spi/ip/axi_spi_microblaze_0_axi_intc_0/axi_spi_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_spi_microblaze_0_axi_intc_0 || ORIG_REF_NAME==axi_spi_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/axi_spi/ip/axi_spi_microblaze_0_xlconcat_0/axi_spi_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_spi_microblaze_0_xlconcat_0 || ORIG_REF_NAME==axi_spi_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/axi_spi/ip/axi_spi_mdm_1_0/axi_spi_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_spi_mdm_1_0 || ORIG_REF_NAME==axi_spi_mdm_1_0} -quiet] -quiet

# IP: bd/axi_spi/ip/axi_spi_clk_wiz_1_0/axi_spi_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_spi_clk_wiz_1_0 || ORIG_REF_NAME==axi_spi_clk_wiz_1_0} -quiet] -quiet

# IP: bd/axi_spi/ip/axi_spi_rst_clk_wiz_1_100M_0/axi_spi_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_spi_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==axi_spi_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/axi_spi/ip/axi_spi_GPIO8_0_0/axi_spi_GPIO8_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_spi_GPIO8_0_0 || ORIG_REF_NAME==axi_spi_GPIO8_0_0} -quiet] -quiet

# IP: bd/axi_spi/ip/axi_spi_GPIO8_1_0/axi_spi_GPIO8_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_spi_GPIO8_1_0 || ORIG_REF_NAME==axi_spi_GPIO8_1_0} -quiet] -quiet

# IP: bd/axi_spi/ip/axi_spi_GPIO8_2_0/axi_spi_GPIO8_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_spi_GPIO8_2_0 || ORIG_REF_NAME==axi_spi_GPIO8_2_0} -quiet] -quiet

# IP: bd/axi_spi/ip/axi_spi_TMR_0_0/axi_spi_TMR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_spi_TMR_0_0 || ORIG_REF_NAME==axi_spi_TMR_0_0} -quiet] -quiet

# IP: bd/axi_spi/ip/axi_spi_axi_spi_0_0/axi_spi_axi_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_spi_axi_spi_0_0 || ORIG_REF_NAME==axi_spi_axi_spi_0_0} -quiet] -quiet

# XDC: d:/pr0503_microblaze_axi_spi_i2c/newmicroblaze_spi/newmicroblaze_spi.gen/sources_1/bd/axi_spi/ip/axi_spi_microblaze_0_0/axi_spi_microblaze_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_spi_microblaze_0_0 || ORIG_REF_NAME==axi_spi_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/pr0503_microblaze_axi_spi_i2c/newmicroblaze_spi/newmicroblaze_spi.gen/sources_1/bd/axi_spi/ip/axi_spi_microblaze_0_0/axi_spi_microblaze_0_0_ooc_debug.xdc

# XDC: d:/pr0503_microblaze_axi_spi_i2c/newmicroblaze_spi/newmicroblaze_spi.gen/sources_1/bd/axi_spi/ip/axi_spi_dlmb_v10_0/axi_spi_dlmb_v10_0_ooc.xdc

# XDC: d:/pr0503_microblaze_axi_spi_i2c/newmicroblaze_spi/newmicroblaze_spi.gen/sources_1/bd/axi_spi/ip/axi_spi_ilmb_v10_0/axi_spi_ilmb_v10_0_ooc.xdc

# XDC: d:/pr0503_microblaze_axi_spi_i2c/newmicroblaze_spi/newmicroblaze_spi.gen/sources_1/bd/axi_spi/ip/axi_spi_dlmb_bram_if_cntlr_0/axi_spi_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: d:/pr0503_microblaze_axi_spi_i2c/newmicroblaze_spi/newmicroblaze_spi.gen/sources_1/bd/axi_spi/ip/axi_spi_ilmb_bram_if_cntlr_0/axi_spi_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: d:/pr0503_microblaze_axi_spi_i2c/newmicroblaze_spi/newmicroblaze_spi.gen/sources_1/bd/axi_spi/ip/axi_spi_lmb_bram_0/axi_spi_lmb_bram_0_ooc.xdc

# XDC: d:/pr0503_microblaze_axi_spi_i2c/newmicroblaze_spi/newmicroblaze_spi.gen/sources_1/bd/axi_spi/ip/axi_spi_xbar_0/axi_spi_xbar_0_ooc.xdc

# XDC: d:/pr0503_microblaze_axi_spi_i2c/newmicroblaze_spi/newmicroblaze_spi.gen/sources_1/bd/axi_spi/ip/axi_spi_microblaze_0_axi_intc_0/axi_spi_microblaze_0_axi_intc_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_spi_microblaze_0_axi_intc_0 || ORIG_REF_NAME==axi_spi_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/pr0503_microblaze_axi_spi_i2c/newmicroblaze_spi/newmicroblaze_spi.gen/sources_1/bd/axi_spi/ip/axi_spi_microblaze_0_axi_intc_0/axi_spi_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_spi_microblaze_0_axi_intc_0 || ORIG_REF_NAME==axi_spi_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/pr0503_microblaze_axi_spi_i2c/newmicroblaze_spi/newmicroblaze_spi.gen/sources_1/bd/axi_spi/ip/axi_spi_microblaze_0_axi_intc_0/axi_spi_microblaze_0_axi_intc_0_ooc.xdc

# XDC: d:/pr0503_microblaze_axi_spi_i2c/newmicroblaze_spi/newmicroblaze_spi.gen/sources_1/bd/axi_spi/ip/axi_spi_mdm_1_0/axi_spi_mdm_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_spi_mdm_1_0 || ORIG_REF_NAME==axi_spi_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/pr0503_microblaze_axi_spi_i2c/newmicroblaze_spi/newmicroblaze_spi.gen/sources_1/bd/axi_spi/ip/axi_spi_mdm_1_0/axi_spi_mdm_1_0_ooc_trace.xdc

# XDC: d:/pr0503_microblaze_axi_spi_i2c/newmicroblaze_spi/newmicroblaze_spi.gen/sources_1/bd/axi_spi/ip/axi_spi_clk_wiz_1_0/axi_spi_clk_wiz_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_spi_clk_wiz_1_0 || ORIG_REF_NAME==axi_spi_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/pr0503_microblaze_axi_spi_i2c/newmicroblaze_spi/newmicroblaze_spi.gen/sources_1/bd/axi_spi/ip/axi_spi_clk_wiz_1_0/axi_spi_clk_wiz_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_spi_clk_wiz_1_0 || ORIG_REF_NAME==axi_spi_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/pr0503_microblaze_axi_spi_i2c/newmicroblaze_spi/newmicroblaze_spi.gen/sources_1/bd/axi_spi/ip/axi_spi_clk_wiz_1_0/axi_spi_clk_wiz_1_0_ooc.xdc

# XDC: d:/pr0503_microblaze_axi_spi_i2c/newmicroblaze_spi/newmicroblaze_spi.gen/sources_1/bd/axi_spi/ip/axi_spi_rst_clk_wiz_1_100M_0/axi_spi_rst_clk_wiz_1_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_spi_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==axi_spi_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/pr0503_microblaze_axi_spi_i2c/newmicroblaze_spi/newmicroblaze_spi.gen/sources_1/bd/axi_spi/ip/axi_spi_rst_clk_wiz_1_100M_0/axi_spi_rst_clk_wiz_1_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_spi_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==axi_spi_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/pr0503_microblaze_axi_spi_i2c/newmicroblaze_spi/newmicroblaze_spi.gen/sources_1/bd/axi_spi/axi_spi_ooc.xdc
